nlsfb_lijst = [
    {'materiaal': 'beton_ntb', 'nlsfb': 'f2'},
    {'materiaal': 'beton_generiek', 'nlsfb': 'f2'},
    {'materiaal': 'beton_bimsbeton', 'nlsfb': 'f2'},
    {'materiaal': 'beton_cellenbeton', 'nlsfb': 'f4'},
    {'materiaal': 'beton_gewapend', 'nlsfb': 'f2'},
    {'materiaal': 'beton_grindbeton', 'nlsfb': 'f2'},
    {'materiaal': 'beton_isolatiebeton', 'nlsfb': 'f5'},
    {'materiaal': 'beton_lichtbeton', 'nlsfb': 'f5'},
    {'materiaal': 'beton_slakkenbeton', 'nlsfb': 'f5'},
    {'materiaal': 'beton_voorgespannen', 'nlsfb': 'f2'},
    {'materiaal': 'beton_schuimbeton', 'nlsfb': 'f4'},
    {'materiaal': 'beton_staalvezelbeton', 'nlsfb': 'f2'},
    {'materiaal': 'beton_spuitbeton', 'nlsfb': 'f2'},
    {'materiaal': 'bitumen_ntb', 'nlsfb': 'n1'},
    {'materiaal': 'bitumen_generiek', 'nlsfb': 'n1'},
    {'materiaal': 'bitumen_asfalt', 'nlsfb': 'n1'},
    {'materiaal': 'bitumen_teer', 'nlsfb': 'n1'},
    {'materiaal': 'cement_ntb', 'nlsfb': 'q1'},
    {'materiaal': 'cement_generiek', 'nlsfb': 'q2'},
    {'materiaal': 'cement_asbestcement', 'nlsfb': 'f6'},
    {'materiaal': 'cement_cementstuc', 'nlsfb': 'f2'},
    {'materiaal': 'cement_grout', 'nlsfb': 'f2'},
    {'materiaal': 'cement_houtvezelcement', 'nlsfb': 'f8'},
    {'materiaal': 'cement_houtwolcement', 'nlsfb': 'f8'},
    {'materiaal': 'cement_metselspecie', 'nlsfb': 'f2'},
    {'materiaal': 'cement_mortel', 'nlsfb': 'f2'},
    {'materiaal': 'cement_spuitmortel', 'nlsfb': 'f2'},
    {'materiaal': 'cement_terrazzo', 'nlsfb': 'f3'},
    {'materiaal': 'cement_vezelcement', 'nlsfb': 'f2'},
    {'materiaal': 'cement_zandcement', 'nlsfb': 'f2'},
    {'materiaal': 'cement_zandcement-vezel', 'nlsfb': 'f5'},
    {'materiaal': 'gips_ntb', 'nlsfb': 'f7'},
    {'materiaal': 'gips_generiek', 'nlsfb': 'f7'},
    {'materiaal': 'gips_anhydriet', 'nlsfb': 'f7'},
    {'materiaal': 'gips_gipskarton', 'nlsfb': 'f7'},
    {'materiaal': 'gips_spuitstuc', 'nlsfb': 'f7'},
    {'materiaal': 'gips_stuc', 'nlsfb': 'f7'},
    {'materiaal': 'glas_ntb', 'nlsfb': 'o'},
    {'materiaal': 'glas_generiek', 'nlsfb': 'o'},
    {'materiaal': 'glas_gehard', 'nlsfb': 'o8'},
    {'materiaal': 'glas_gewapend', 'nlsfb': 'o4'},
    {'materiaal': 'glas_helder', 'nlsfb': 'o1'},
    {'materiaal': 'glas_kwartsglas', 'nlsfb': 'o1'},
    {'materiaal': 'glas_ondoorzichtig', 'nlsfb': 'o3'},
    {'materiaal': 'glas_spiegelend', 'nlsfb': 'o6'},
    {'materiaal': 'glas_translucent', 'nlsfb': 'o3'},
    {'materiaal': 'grondstof_aarde', 'nlsfb': 'p1'},
    {'materiaal': 'grondstof_bimszand', 'nlsfb': 'p3'},
    {'materiaal': 'grondstof_grind', 'nlsfb': 'p1'},
    {'materiaal': 'grondstof_kalk', 'nlsfb': 'q1'},
    {'materiaal': 'grondstof_klei', 'nlsfb': 'g1'},
    {'materiaal': 'grondstof_leem', 'nlsfb': 'g1'},
    {'materiaal': 'grondstof_lucht', 'nlsfb': 'z1'},
    {'materiaal': 'grondstof_silt', 'nlsfb': 'g1'},
    {'materiaal': 'grondstof_split', 'nlsfb': 'p1'},
    {'materiaal': 'grondstof_turf', 'nlsfb': 'j9'},
    {'materiaal': 'grondstof_water', 'nlsfb': 'w4'},
    {'materiaal': 'grondstof_zand', 'nlsfb': 'p1'},
    {'materiaal': 'hout_ntb', 'nlsfb': 'i1'},
    {'materiaal': 'hout_generiek', 'nlsfb': 'i1'},
    {'materiaal': 'hout_accoya', 'nlsfb': 'i2'},
    {'materiaal': 'hout_azobe', 'nlsfb': 'i3'},
    {'materiaal': 'hout_balsa', 'nlsfb': 'i3'},
    {'materiaal': 'hout_bangkirai', 'nlsfb': 'i3'},
    {'materiaal': 'hout_berken', 'nlsfb': 'i2'},
    {'materiaal': 'hout_beuken', 'nlsfb': 'i2'},
    {'materiaal': 'hout_bilinga', 'nlsfb': 'i3'},
    {'materiaal': 'hout_board', 'nlsfb': 'j1'},
    {'materiaal': 'hout_clt', 'nlsfb': 'i2'},
    {'materiaal': 'hout_douglas', 'nlsfb': 'i2'},
    {'materiaal': 'hout_ebben', 'nlsfb': 'i3'},
    {'materiaal': 'hout_eiken', 'nlsfb': 'i3'},
    {'materiaal': 'hout_esdoorn', 'nlsfb': 'i3'},
    {'materiaal': 'hout_essen', 'nlsfb': 'i3'},
    {'materiaal': 'hout_gemodificeerd', 'nlsfb': 'i2'},
    {'materiaal': 'hout_grenen', 'nlsfb': 'i2'},
    {'materiaal': 'hout_hardboard', 'nlsfb': 'j1'},
    {'materiaal': 'hout_hardhout', 'nlsfb': 'i3'},
    {'materiaal': 'hout_houtspaan', 'nlsfb': 'j1'},
    {'materiaal': 'hout_houtvezel', 'nlsfb': 'j1'},
    {'materiaal': 'hout_houtwol', 'nlsfb': 'j1'},
    {'materiaal': 'hout_kersen', 'nlsfb': 'i3'},
    {'materiaal': 'hout_lariks', 'nlsfb': 'i2'},
    {'materiaal': 'hout_mahonie', 'nlsfb': 'i3'},
    {'materiaal': 'hout_masonite', 'nlsfb': 'i1'},
    {'materiaal': 'hout_mdf', 'nlsfb': 'j1'},
    {'materiaal': 'hout_meranti', 'nlsfb': 'i3'},
    {'materiaal': 'hout_merbau', 'nlsfb': 'i3'},
    {'materiaal': 'hout_multiplex', 'nlsfb': 'i4'},
    {'materiaal': 'hout_noten', 'nlsfb': 'i3'},
    {'materiaal': 'hout_okoume', 'nlsfb': 'i3'},
    {'materiaal': 'hout_osb', 'nlsfb': 'j7'},
    {'materiaal': 'hout_populieren', 'nlsfb': 'i2'},
    {'materiaal': 'hout_spaanplaat', 'nlsfb': 'j1'},
    {'materiaal': 'hout_triplex', 'nlsfb': 'i4'},
    {'materiaal': 'hout_vuren', 'nlsfb': 'i2'},
    {'materiaal': 'hout_wenge', 'nlsfb': 'i3'},
    {'materiaal': 'hout_ceder', 'nlsfb': 'i2'},
    {'materiaal': 'hout_zaagsel', 'nlsfb': 'p5'},
    {'materiaal': 'hout_zachtboard', 'nlsfb': 'j1'},
    {'materiaal': 'hout_zachthout', 'nlsfb': 'i2'},
    {'materiaal': 'isolatie_cellulairglas', 'nlsfb': 'o9'},
    {'materiaal': 'isolatie_eps', 'nlsfb': 'n7'},
    {'materiaal': 'isolatie_fenolhars', 'nlsfb': 'n6'},
    {'materiaal': 'isolatie_glaswol', 'nlsfb': 'm1'},
    {'materiaal': 'isolatie_geexpandeerd-perliet', 'nlsfb': 'o9'},
    {'materiaal': 'isolatie_hardschuim', 'nlsfb': 'n7'},
    {'materiaal': 'isolatie_mineralewol', 'nlsfb': 'm1'},
    {'materiaal': 'isolatie_mineraal', 'nlsfb': 'm1'},
    {'materiaal': 'isolatie_resolschuim', 'nlsfb': 'n7'},
    {'materiaal': 'isolatie_siliperliet', 'nlsfb': 'o9'},
    {'materiaal': 'isolatie_pir', 'nlsfb': 'n7'},
    {'materiaal': 'isolatie_pur', 'nlsfb': 'n7'},
    {'materiaal': 'isolatie_solperlite', 'nlsfb': 'o9'},
    {'materiaal': 'isolatie_steenwol', 'nlsfb': 'm1'},
    {'materiaal': 'isolatie_xps', 'nlsfb': 'n7'},
    {'materiaal': 'kunststof_ntb', 'nlsfb': 'n'},
    {'materiaal': 'kunststof_generiek', 'nlsfb': 'n'},
    {'materiaal': 'kunststof_abs', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_acryl', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_dpc', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_elastomere-foam', 'nlsfb': 'n7'},
    {'materiaal': 'kunststof_ep', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_epoxyhars', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_hard-kunststof', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_hdpe', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_hmpe', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_hpl', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_ldpe', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_loodvervanger', 'nlsfb': 'n'},
    {'materiaal': 'kunststof_pe', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pmma', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pa', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pc', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pctfe', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_plexiglas', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_polyesterhars', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_polyester', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pom', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pp', 'nlsfb': 'n7'},
    {'materiaal': 'kunststof_ps', 'nlsfb': 'n7'},
    {'materiaal': 'kunststof_ptfe', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pu', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pvac', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_pvc', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_zacht-kunststof', 'nlsfb': 'n6'},
    {'materiaal': 'kunststof_silicagel', 'nlsfb': 'n7'},
    {'materiaal': 'kunststof_siliconen', 'nlsfb': 'n6'},
    {'materiaal': 'metaal_ntb', 'nlsfb': 'h1'},
    {'materiaal': 'metaal_generiek', 'nlsfb': 'h1'},
    {'materiaal': 'metaal_aluminium', 'nlsfb': 'h4'},
    {'materiaal': 'metaal_brons', 'nlsfb': 'h6'},
    {'materiaal': 'metaal_chroom', 'nlsfb': 'h9'},
    {'materiaal': 'metaal_gietijzer', 'nlsfb': 'h1'},
    {'materiaal': 'metaal_goud', 'nlsfb': 'h9'},
    {'materiaal': 'metaal_ijzer', 'nlsfb': 'h2'},
    {'materiaal': 'metaal_koper', 'nlsfb': 'h5'},
    {'materiaal': 'metaal_lood', 'nlsfb': 'h8'},
    {'materiaal': 'metaal_messing', 'nlsfb': 'h6'},
    {'materiaal': 'metaal_platina', 'nlsfb': 'h9'},
    {'materiaal': 'metaal_rvs', 'nlsfb': 'h3'},
    {'materiaal': 'metaal_soldeersel', 'nlsfb': 't2'},
    {'materiaal': 'metaal_staal', 'nlsfb': 'h2'},
    {'materiaal': 'metaal_tin', 'nlsfb': 'h9'},
    {'materiaal': 'metaal_titanium', 'nlsfb': 'h9'},
    {'materiaal': 'metaal_zilver', 'nlsfb': 'h9'},
    {'materiaal': 'metaal_zink', 'nlsfb': 'h7'},
    {'materiaal': 'natuursteen_ntb', 'nlsfb': 'e1'},
    {'materiaal': 'natuursteen_generiek', 'nlsfb': 'e1'},
    {'materiaal': 'natuursteen_asbest', 'nlsfb': 'm2'},
    {'materiaal': 'natuursteen_basalt', 'nlsfb': 'e1'},
    {'materiaal': 'natuursteen_gneiss', 'nlsfb': 'e1'},
    {'materiaal': 'natuursteen_graniet', 'nlsfb': 'e1'},
    {'materiaal': 'natuursteen_gravel', 'nlsfb': 'p2'},
    {'materiaal': 'natuursteen_hardsteen', 'nlsfb': 'e3'},
    {'materiaal': 'natuursteen_kristallijn-gesteente', 'nlsfb': 'e1'},
    {'materiaal': 'natuursteen_kwartsiet', 'nlsfb': 'e9'},
    {'materiaal': 'natuursteen_lei', 'nlsfb': 'e5'},
    {'materiaal': 'natuursteen_marmer', 'nlsfb': 'e2'},
    {'materiaal': 'natuursteen_poreus-gesteente', 'nlsfb': 'e1'},
    {'materiaal': 'natuursteen_puimsteen', 'nlsfb': 'e1'},
    {'materiaal': 'natuursteen_sedimentgesteente', 'nlsfb': 'z3'},
    {'materiaal': 'natuursteen_trachiet', 'nlsfb': 'e9'},
    {'materiaal': 'natuursteen_travertin', 'nlsfb': 'e3'},
    {'materiaal': 'natuursteen_zandsteen', 'nlsfb': 'e4'},
    {'materiaal': 'organisch_ntb', 'nlsfb': 'j'},
    {'materiaal': 'organisch_generiek', 'nlsfb': 'j'},
    {'materiaal': 'organisch_bamboe', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_hennep', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_jute', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_katoen', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_kurk', 'nlsfb': 'j5'},
    {'materiaal': 'organisch_leer', 'nlsfb': 'j6'},
    {'materiaal': 'organisch_mais', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_papier', 'nlsfb': 'j2'},
    {'materiaal': 'organisch_plantaardige-vezel', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_riet', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_stro', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_vegetatie', 'nlsfb': 'j6'},
    {'materiaal': 'organisch_vilt', 'nlsfb': 'j6'},
    {'materiaal': 'organisch_vlas', 'nlsfb': 'j3'},
    {'materiaal': 'organisch_wol', 'nlsfb': 'j6'},
    {'materiaal': 'rubber_ntb', 'nlsfb': 'n1'},
    {'materiaal': 'rubber_generiek', 'nlsfb': 'n1'},
    {'materiaal': 'rubber_butyl', 'nlsfb': 'n5'},
    {'materiaal': 'rubber_epdm', 'nlsfb': 'n5'},
    {'materiaal': 'rubber_hard-rubber', 'nlsfb': 'n5'},
    {'materiaal': 'rubber_linoleum', 'nlsfb': 'n4'},
    {'materiaal': 'rubber_natuurrubber', 'nlsfb': 'n5'},
    {'materiaal': 'rubber_neopreen', 'nlsfb': 'n5'},
    {'materiaal': 'rubber_polysulfide', 'nlsfb': 'n5'},
    {'materiaal': 'rubber_schuimrubber', 'nlsfb': 'n6'},
    {'materiaal': 'rubber_tpve', 'nlsfb': 'n7'},
    {'materiaal': 'samengesteld_element', 'nlsfb': 'a'},
    {'materiaal': 'samengesteld_product', 'nlsfb': 'a'},
    {'materiaal': 'steenachtig_baksteen', 'nlsfb': 'g2'},
    {'materiaal': 'steenachtig_calciumsilicaat', 'nlsfb': 'f1'},
    {'materiaal': 'steenachtig_geexpandeerde-klei', 'nlsfb': 'p3'},
    {'materiaal': 'steenachtig_kalksteen', 'nlsfb': 'e3'},
    {'materiaal': 'steenachtig_kalkzandsteen', 'nlsfb': 'f1'},
    {'materiaal': 'steenachtig_keramisch', 'nlsfb': 'g2'},
    {'materiaal': 'steenachtig_kunststeen', 'nlsfb': 'f3'},
    {'materiaal': 'steenachtig_porisosteen', 'nlsfb': 'g2'},
    {'materiaal': 'steenachtig_porselein', 'nlsfb': 'g3'}
]

ral_lijst = [
    {'code': 'ral1000', 'r': 205, 'g': 186, 'b': 136, 'omschrijving': 'groenbeige'},
    {'code': 'ral1001', 'r': 208, 'g': 176, 'b': 132, 'omschrijving': 'beige'},
    {'code': 'ral1002', 'r': 210, 'g': 170, 'b': 109, 'omschrijving': 'zandgeel'},
    {'code': 'ral1003', 'r': 249, 'g': 168, 'b': 0, 'omschrijving': 'signaalgeel'},
    {'code': 'ral1004', 'r': 228, 'g': 158, 'b': 0, 'omschrijving': 'goudgeel'},
    {'code': 'ral1005', 'r': 203, 'g': 142, 'b': 0, 'omschrijving': 'honinggeel'},
    {'code': 'ral1006', 'r': 226, 'g': 144, 'b': 0, 'omschrijving': 'maisgeel'},
    {'code': 'ral1007', 'r': 232, 'g': 140, 'b': 0, 'omschrijving': 'narcissengeel'},
    {'code': 'ral1011', 'r': 175, 'g': 128, 'b': 79, 'omschrijving': 'bruinbeige'},
    {'code': 'ral1012', 'r': 221, 'g': 175, 'b': 39, 'omschrijving': 'citroengeel'},
    {'code': 'ral1013', 'r': 227, 'g': 217, 'b': 198, 'omschrijving': 'parelwit'},
    {'code': 'ral1014', 'r': 221, 'g': 196, 'b': 154, 'omschrijving': 'ivoorkleur'},
    {'code': 'ral1015', 'r': 230, 'g': 210, 'b': 181, 'omschrijving': 'licht ivoorkleur'},
    {'code': 'ral1016', 'r': 241, 'g': 221, 'b': 56, 'omschrijving': 'zwavelgeel'},
    {'code': 'ral1017', 'r': 246, 'g': 169, 'b': 80, 'omschrijving': 'saffraangeel'},
    {'code': 'ral1018', 'r': 250, 'g': 202, 'b': 48, 'omschrijving': 'zinkgeel'},
    {'code': 'ral1019', 'r': 164, 'g': 143, 'b': 122, 'omschrijving': 'grijsbeige'},
    {'code': 'ral1020', 'r': 160, 'g': 143, 'b': 101, 'omschrijving': 'olijfgeel'},
    {'code': 'ral1021', 'r': 246, 'g': 182, 'b': 0, 'omschrijving': 'koolzaadgeel'},
    {'code': 'ral1023', 'r': 247, 'g': 181, 'b': 0, 'omschrijving': 'verkeersgeel'},
    {'code': 'ral1024', 'r': 186, 'g': 143, 'b': 76, 'omschrijving': 'okergeel'},
    {'code': 'ral1026', 'r': 255, 'g': 255, 'b': 0, 'omschrijving': 'briljantgeel'},
    {'code': 'ral1027', 'r': 167, 'g': 127, 'b': 14, 'omschrijving': 'kerriegeel'},
    {'code': 'ral1028', 'r': 255, 'g': 155, 'b': 0, 'omschrijving': 'meloengeel'},
    {'code': 'ral1032', 'r': 226, 'g': 163, 'b': 0, 'omschrijving': 'bremgeel'},
    {'code': 'ral1033', 'r': 249, 'g': 154, 'b': 28, 'omschrijving': 'dahliageel'},
    {'code': 'ral1034', 'r': 235, 'g': 156, 'b': 82, 'omschrijving': 'pastelgeel'},
    {'code': 'ral1035', 'r': 144, 'g': 131, 'b': 112, 'omschrijving': 'parelmoer grijs'},
    {'code': 'ral1036', 'r': 128, 'g': 100, 'b': 63, 'omschrijving': 'parelmoer goud'},
    {'code': 'ral1037', 'r': 240, 'g': 146, 'b': 0, 'omschrijving': 'zonnegeel'},
    {'code': 'ral2000', 'r': 218, 'g': 110, 'b': 0, 'omschrijving': 'geeloranje'},
    {'code': 'ral2001', 'r': 186, 'g': 72, 'b': 27, 'omschrijving': 'roodoranje'},
    {'code': 'ral2002', 'r': 191, 'g': 57, 'b': 34, 'omschrijving': 'vermiljoen'},
    {'code': 'ral2003', 'r': 246, 'g': 120, 'b': 40, 'omschrijving': 'pasteloranje'},
    {'code': 'ral2004', 'r': 226, 'g': 83, 'b': 3, 'omschrijving': 'zuiver oranje'},
    {'code': 'ral2005', 'r': 255, 'g': 77, 'b': 6, 'omschrijving': 'briljant oranje'},
    {'code': 'ral2007', 'r': 255, 'g': 178, 'b': 0, 'omschrijving': 'briljant lichtoranje'},
    {'code': 'ral2008', 'r': 237, 'g': 107, 'b': 33, 'omschrijving': 'licht roodoranje'},
    {'code': 'ral2009', 'r': 222, 'g': 83, 'b': 7, 'omschrijving': 'verkeersoranje'},
    {'code': 'ral2010', 'r': 208, 'g': 93, 'b': 40, 'omschrijving': 'signaaloranje'},
    {'code': 'ral2011', 'r': 226, 'g': 110, 'b': 14, 'omschrijving': 'dieporanje'},
    {'code': 'ral2012', 'r': 213, 'g': 101, 'b': 77, 'omschrijving': 'zalmoranje'},
    {'code': 'ral2013', 'r': 146, 'g': 62, 'b': 37, 'omschrijving': 'parelmoer oranje'},
    {'code': 'ral3000', 'r': 167, 'g': 41, 'b': 32, 'omschrijving': 'vuurrood'},
    {'code': 'ral3001', 'r': 155, 'g': 36, 'b': 35, 'omschrijving': 'signaalrood'},
    {'code': 'ral3002', 'r': 155, 'g': 35, 'b': 33, 'omschrijving': 'karmijnrood'},
    {'code': 'ral3003', 'r': 134, 'g': 26, 'b': 34, 'omschrijving': 'robijnrood'},
    {'code': 'ral3004', 'r': 107, 'g': 28, 'b': 35, 'omschrijving': 'purperrood'},
    {'code': 'ral3005', 'r': 89, 'g': 25, 'b': 31, 'omschrijving': 'wijnrood'},
    {'code': 'ral3007', 'r': 62, 'g': 32, 'b': 34, 'omschrijving': 'zwartrood'},
    {'code': 'ral3009', 'r': 100, 'g': 36, 'b': 36, 'omschrijving': 'oxyderood'},
    {'code': 'ral3011', 'r': 121, 'g': 36, 'b': 35, 'omschrijving': 'bruinrood'},
    {'code': 'ral3012', 'r': 198, 'g': 132, 'b': 109, 'omschrijving': 'beigerood'},
    {'code': 'ral3013', 'r': 151, 'g': 46, 'b': 37, 'omschrijving': 'tomaatrood'},
    {'code': 'ral3014', 'r': 203, 'g': 115, 'b': 117, 'omschrijving': 'oudroze'},
    {'code': 'ral3015', 'r': 216, 'g': 160, 'b': 166, 'omschrijving': 'lichtroze'},
    {'code': 'ral3016', 'r': 166, 'g': 61, 'b': 47, 'omschrijving': 'koraalrood'},
    {'code': 'ral3017', 'r': 203, 'g': 85, 'b': 93, 'omschrijving': 'bleekrood'},
    {'code': 'ral3018', 'r': 199, 'g': 3, 'b': 74, 'omschrijving': 'aardbeirood'},
    {'code': 'ral3020', 'r': 187, 'g': 30, 'b': 16, 'omschrijving': 'verkeersrood'},
    {'code': 'ral3022', 'r': 207, 'g': 105, 'b': 85, 'omschrijving': 'zalmrood'},
    {'code': 'ral3024', 'r': 255, 'g': 45, 'b': 33, 'omschrijving': 'briljant rood'},
    {'code': 'ral3026', 'r': 255, 'g': 42, 'b': 27, 'omschrijving': 'briljant lichtrood'},
    {'code': 'ral3027', 'r': 171, 'g': 39, 'b': 60, 'omschrijving': 'framboosrood'},
    {'code': 'ral3028', 'r': 204, 'g': 44, 'b': 36, 'omschrijving': 'zuiverrood'},
    {'code': 'ral3031', 'r': 166, 'g': 52, 'b': 55, 'omschrijving': 'oriëntrood'},
    {'code': 'ral3032', 'r': 112, 'g': 29, 'b': 35, 'omschrijving': 'parelmoer donkerrood'},
    {'code': 'ral3033', 'r': 165, 'g': 58, 'b': 45, 'omschrijving': 'parelmoer lichtrood'},
    {'code': 'ral4001', 'r': 129, 'g': 97, 'b': 131, 'omschrijving': 'roodlila'},
    {'code': 'ral4002', 'r': 141, 'g': 60, 'b': 75, 'omschrijving': 'roodpaars'},
    {'code': 'ral4003', 'r': 196, 'g': 97, 'b': 140, 'omschrijving': 'heidepaars'},
    {'code': 'ral4004', 'r': 101, 'g': 30, 'b': 56, 'omschrijving': 'bordeauxpaars'},
    {'code': 'ral4005', 'r': 118, 'g': 104, 'b': 154, 'omschrijving': 'blauwlila'},
    {'code': 'ral4006', 'r': 144, 'g': 51, 'b': 115, 'omschrijving': 'verkeerspurper'},
    {'code': 'ral4007', 'r': 71, 'g': 36, 'b': 60, 'omschrijving': 'purperviolet'},
    {'code': 'ral4008', 'r': 132, 'g': 76, 'b': 130, 'omschrijving': 'signaalviolet'},
    {'code': 'ral4009', 'r': 157, 'g': 134, 'b': 146, 'omschrijving': 'pastelviolet'},
    {'code': 'ral4010', 'r': 188, 'g': 64, 'b': 119, 'omschrijving': 'telemagenta'},
    {'code': 'ral4011', 'r': 110, 'g': 99, 'b': 135, 'omschrijving': 'parelmoer donkerviolet'},
    {'code': 'ral4012', 'r': 107, 'g': 107, 'b': 127, 'omschrijving': 'parelmoer lichtviolet'},
    {'code': 'ral5000', 'r': 49, 'g': 79, 'b': 111, 'omschrijving': 'paarsblauw'},
    {'code': 'ral5001', 'r': 15, 'g': 76, 'b': 100, 'omschrijving': 'groenblauw'},
    {'code': 'ral5002', 'r': 0, 'g': 56, 'b': 123, 'omschrijving': 'ultramarijnblauw'},
    {'code': 'ral5003', 'r': 31, 'g': 56, 'b': 85, 'omschrijving': 'saffierblauw'},
    {'code': 'ral5004', 'r': 25, 'g': 30, 'b': 40, 'omschrijving': 'zwartblauw'},
    {'code': 'ral5005', 'r': 0, 'g': 83, 'b': 135, 'omschrijving': 'signaalblauw'},
    {'code': 'ral5007', 'r': 55, 'g': 107, 'b': 140, 'omschrijving': 'briljantblauw'},
    {'code': 'ral5008', 'r': 43, 'g': 58, 'b': 68, 'omschrijving': 'grijsblauw'},
    {'code': 'ral5009', 'r': 34, 'g': 95, 'b': 120, 'omschrijving': 'azuurblauw'},
    {'code': 'ral5010', 'r': 0, 'g': 79, 'b': 124, 'omschrijving': 'gentiaanblauw'},
    {'code': 'ral5011', 'r': 26, 'g': 43, 'b': 60, 'omschrijving': 'staalblauw'},
    {'code': 'ral5012', 'r': 0, 'g': 137, 'b': 182, 'omschrijving': 'lichtblauw'},
    {'code': 'ral5013', 'r': 25, 'g': 49, 'b': 83, 'omschrijving': 'kobaltblauw'},
    {'code': 'ral5014', 'r': 99, 'g': 125, 'b': 150, 'omschrijving': 'duifblauw'},
    {'code': 'ral5015', 'r': 0, 'g': 124, 'b': 176, 'omschrijving': 'hemelsblauw'},
    {'code': 'ral5017', 'r': 0, 'g': 91, 'b': 140, 'omschrijving': 'verkeersblauw'},
    {'code': 'ral5018', 'r': 5, 'g': 139, 'b': 140, 'omschrijving': 'turkooisblauw'},
    {'code': 'ral5019', 'r': 0, 'g': 94, 'b': 131, 'omschrijving': 'capriblauw'},
    {'code': 'ral5020', 'r': 0, 'g': 65, 'b': 75, 'omschrijving': 'oceaanblauw'},
    {'code': 'ral5021', 'r': 0, 'g': 117, 'b': 119, 'omschrijving': 'waterblauw'},
    {'code': 'ral5022', 'r': 34, 'g': 45, 'b': 90, 'omschrijving': 'nachtblauw'},
    {'code': 'ral5023', 'r': 6, 'g': 105, 'b': 140, 'omschrijving': 'verblauw'},
    {'code': 'ral5024', 'r': 9, 'g': 147, 'b': 172, 'omschrijving': 'pastelblauw'},
    {'code': 'ral5025', 'r': 33, 'g': 105, 'b': 124, 'omschrijving': 'parelmoer blauw'},
    {'code': 'ral5026', 'r': 15, 'g': 48, 'b': 82, 'omschrijving': 'parelmoer nachtblauw'},
    {'code': 'ral6000', 'r': 60, 'g': 116, 'b': 96, 'omschrijving': 'patinagroen'},
    {'code': 'ral6001', 'r': 54, 'g': 103, 'b': 53, 'omschrijving': 'smaragdgroen'},
    {'code': 'ral6002', 'r': 50, 'g': 89, 'b': 40, 'omschrijving': 'loofgroen'},
    {'code': 'ral6003', 'r': 80, 'g': 83, 'b': 60, 'omschrijving': 'olijfgroen'},
    {'code': 'ral6004', 'r': 2, 'g': 68, 'b': 66, 'omschrijving': 'blauwgroen'},
    {'code': 'ral6005', 'r': 17, 'g': 66, 'b': 50, 'omschrijving': 'mosgroen'},
    {'code': 'ral6006', 'r': 60, 'g': 57, 'b': 46, 'omschrijving': 'grijs olijfgroen'},
    {'code': 'ral6007', 'r': 44, 'g': 50, 'b': 34, 'omschrijving': 'flessegroen'},
    {'code': 'ral6008', 'r': 55, 'g': 52, 'b': 42, 'omschrijving': 'bruingroen'},
    {'code': 'ral6009', 'r': 39, 'g': 53, 'b': 42, 'omschrijving': 'dennegroen'},
    {'code': 'ral6010', 'r': 77, 'g': 111, 'b': 57, 'omschrijving': 'grasgroen'},
    {'code': 'ral6011', 'r': 108, 'g': 124, 'b': 89, 'omschrijving': 'resedagroen'},
    {'code': 'ral6012', 'r': 48, 'g': 61, 'b': 58, 'omschrijving': 'zwartgroen'},
    {'code': 'ral6013', 'r': 125, 'g': 118, 'b': 90, 'omschrijving': 'rietgroen'},
    {'code': 'ral6014', 'r': 71, 'g': 65, 'b': 53, 'omschrijving': 'geel olijfgroen'},
    {'code': 'ral6015', 'r': 61, 'g': 61, 'b': 54, 'omschrijving': 'zwart olijfgroen'},
    {'code': 'ral6016', 'r': 0, 'g': 105, 'b': 76, 'omschrijving': 'turkooisgroen'},
    {'code': 'ral6017', 'r': 88, 'g': 127, 'b': 64, 'omschrijving': 'meigroen'},
    {'code': 'ral6018', 'r': 97, 'g': 153, 'b': 59, 'omschrijving': 'geelgroen'},
    {'code': 'ral6019', 'r': 185, 'g': 206, 'b': 172, 'omschrijving': 'witgroen'},
    {'code': 'ral6020', 'r': 55, 'g': 66, 'b': 47, 'omschrijving': 'chroom oxydegroen'},
    {'code': 'ral6021', 'r': 138, 'g': 153, 'b': 119, 'omschrijving': 'bleekgroen'},
    {'code': 'ral6022', 'r': 58, 'g': 51, 'b': 39, 'omschrijving': 'bruin olijfgroen'},
    {'code': 'ral6024', 'r': 0, 'g': 131, 'b': 81, 'omschrijving': 'verkeersgroen'},
    {'code': 'ral6025', 'r': 94, 'g': 110, 'b': 59, 'omschrijving': 'varengroen'},
    {'code': 'ral6026', 'r': 0, 'g': 95, 'b': 78, 'omschrijving': 'opaalgroen'},
    {'code': 'ral6027', 'r': 126, 'g': 186, 'b': 181, 'omschrijving': 'lichtgroen'},
    {'code': 'ral6028', 'r': 49, 'g': 84, 'b': 66, 'omschrijving': 'pijnboomgroen'},
    {'code': 'ral6029', 'r': 0, 'g': 111, 'b': 61, 'omschrijving': 'mintgroen'},
    {'code': 'ral6032', 'r': 35, 'g': 127, 'b': 82, 'omschrijving': 'signaalgroen'},
    {'code': 'ral6033', 'r': 70, 'g': 135, 'b': 127, 'omschrijving': 'mintturquoise'},
    {'code': 'ral6034', 'r': 122, 'g': 172, 'b': 172, 'omschrijving': 'pastelturquoise'},
    {'code': 'ral6035', 'r': 25, 'g': 77, 'b': 37, 'omschrijving': 'parelmoer donkergroen'},
    {'code': 'ral6036', 'r': 4, 'g': 87, 'b': 75, 'omschrijving': 'parelmoer lichtgroen'},
    {'code': 'ral6037', 'r': 0, 'g': 139, 'b': 41, 'omschrijving': 'zuivergroen'},
    {'code': 'ral6038', 'r': 0, 'g': 181, 'b': 26, 'omschrijving': 'briljantgroen'},
    {'code': 'ral7000', 'r': 122, 'g': 136, 'b': 142, 'omschrijving': 'pelsgrijs'},
    {'code': 'ral7001', 'r': 140, 'g': 150, 'b': 157, 'omschrijving': 'zilvergrijs'},
    {'code': 'ral7002', 'r': 129, 'g': 120, 'b': 99, 'omschrijving': 'olijfgrijs'},
    {'code': 'ral7003', 'r': 122, 'g': 118, 'b': 105, 'omschrijving': 'mosgrijs'},
    {'code': 'ral7004', 'r': 155, 'g': 155, 'b': 155, 'omschrijving': 'signaalgrijs'},
    {'code': 'ral7005', 'r': 108, 'g': 110, 'b': 107, 'omschrijving': 'muisgrijs'},
    {'code': 'ral7006', 'r': 118, 'g': 106, 'b': 94, 'omschrijving': 'beigegrijs'},
    {'code': 'ral7008', 'r': 116, 'g': 94, 'b': 61, 'omschrijving': 'kakigrijs'},
    {'code': 'ral7009', 'r': 93, 'g': 96, 'b': 88, 'omschrijving': 'groengrijs'},
    {'code': 'ral7010', 'r': 88, 'g': 92, 'b': 86, 'omschrijving': 'zeildoekgrijs'},
    {'code': 'ral7011', 'r': 82, 'g': 89, 'b': 93, 'omschrijving': 'ijzergrijs'},
    {'code': 'ral7012', 'r': 87, 'g': 93, 'b': 94, 'omschrijving': 'bazaltgrijs'},
    {'code': 'ral7013', 'r': 87, 'g': 80, 'b': 68, 'omschrijving': 'bruingrijs'},
    {'code': 'ral7015', 'r': 79, 'g': 83, 'b': 88, 'omschrijving': 'leigrijs'},
    {'code': 'ral7016', 'r': 56, 'g': 62, 'b': 66, 'omschrijving': 'antracietgrijs'},
    {'code': 'ral7021', 'r': 47, 'g': 50, 'b': 52, 'omschrijving': 'zwartgrijs'},
    {'code': 'ral7022', 'r': 76, 'g': 74, 'b': 68, 'omschrijving': 'ombergrijs'},
    {'code': 'ral7023', 'r': 128, 'g': 128, 'b': 118, 'omschrijving': 'betongrijs'},
    {'code': 'ral7024', 'r': 71, 'g': 74, 'b': 81, 'omschrijving': 'grafietgrijs'},
    {'code': 'ral7026', 'r': 55, 'g': 67, 'b': 69, 'omschrijving': 'granietgrijs'},
    {'code': 'ral7030', 'r': 146, 'g': 142, 'b': 133, 'omschrijving': 'steengrijs'},
    {'code': 'ral7031', 'r': 91, 'g': 104, 'b': 109, 'omschrijving': 'blauwgrijs'},
    {'code': 'ral7032', 'r': 181, 'g': 176, 'b': 161, 'omschrijving': 'kiezelgrijs'},
    {'code': 'ral7033', 'r': 127, 'g': 130, 'b': 116, 'omschrijving': 'cementgrijs'},
    {'code': 'ral7034', 'r': 146, 'g': 136, 'b': 111, 'omschrijving': 'geelgrijs'},
    {'code': 'ral7035', 'r': 197, 'g': 199, 'b': 196, 'omschrijving': 'lichtgrijs'},
    {'code': 'ral7036', 'r': 151, 'g': 147, 'b': 146, 'omschrijving': 'platinagrijs'},
    {'code': 'ral7037', 'r': 122, 'g': 123, 'b': 122, 'omschrijving': 'stofgrijs'},
    {'code': 'ral7038', 'r': 176, 'g': 176, 'b': 169, 'omschrijving': 'agaatgrijs'},
    {'code': 'ral7039', 'r': 107, 'g': 102, 'b': 94, 'omschrijving': 'kwartsgrijs'},
    {'code': 'ral7040', 'r': 152, 'g': 158, 'b': 161, 'omschrijving': 'venstergrijs'},
    {'code': 'ral7042', 'r': 142, 'g': 146, 'b': 145, 'omschrijving': 'verkeesgrijs a'},
    {'code': 'ral7043', 'r': 79, 'g': 82, 'b': 80, 'omschrijving': 'verkeersgrijs b'},
    {'code': 'ral7044', 'r': 183, 'g': 179, 'b': 168, 'omschrijving': 'zijdegrijs'},
    {'code': 'ral7045', 'r': 141, 'g': 146, 'b': 149, 'omschrijving': 'telegrijs 1'},
    {'code': 'ral7046', 'r': 127, 'g': 134, 'b': 138, 'omschrijving': 'telegrijs 2'},
    {'code': 'ral7047', 'r': 200, 'g': 200, 'b': 199, 'omschrijving': 'telegrijs 4'},
    {'code': 'ral7048', 'r': 129, 'g': 123, 'b': 115, 'omschrijving': 'parelmoer muisgrijs'},
    {'code': 'ral8000', 'r': 137, 'g': 105, 'b': 62, 'omschrijving': 'groenbruin'},
    {'code': 'ral8001', 'r': 157, 'g': 98, 'b': 43, 'omschrijving': 'okerbruin'},
    {'code': 'ral8002', 'r': 121, 'g': 77, 'b': 62, 'omschrijving': 'signaalbruin'},
    {'code': 'ral8003', 'r': 126, 'g': 75, 'b': 38, 'omschrijving': 'leembruin'},
    {'code': 'ral8004', 'r': 141, 'g': 73, 'b': 49, 'omschrijving': 'koperbruin'},
    {'code': 'ral8007', 'r': 112, 'g': 69, 'b': 42, 'omschrijving': 'reebruin'},
    {'code': 'ral8008', 'r': 114, 'g': 74, 'b': 37, 'omschrijving': 'olijfbruin'},
    {'code': 'ral8011', 'r': 90, 'g': 56, 'b': 38, 'omschrijving': 'notebruin'},
    {'code': 'ral8012', 'r': 102, 'g': 51, 'b': 43, 'omschrijving': 'roodbruin'},
    {'code': 'ral8014', 'r': 74, 'g': 53, 'b': 38, 'omschrijving': 'sepiabruin'},
    {'code': 'ral8015', 'r': 94, 'g': 47, 'b': 38, 'omschrijving': 'kastanjebruin'},
    {'code': 'ral8016', 'r': 76, 'g': 43, 'b': 32, 'omschrijving': 'mahoniebruin'},
    {'code': 'ral8017', 'r': 68, 'g': 47, 'b': 41, 'omschrijving': 'chocoladebruin'},
    {'code': 'ral8019', 'r': 61, 'g': 54, 'b': 53, 'omschrijving': 'grijsbruin'},
    {'code': 'ral8022', 'r': 26, 'g': 23, 'b': 24, 'omschrijving': 'zwartbruin'},
    {'code': 'ral8023', 'r': 164, 'g': 87, 'b': 41, 'omschrijving': 'oranjebruin'},
    {'code': 'ral8024', 'r': 121, 'g': 80, 'b': 56, 'omschrijving': 'beigebruin'},
    {'code': 'ral8025', 'r': 117, 'g': 88, 'b': 71, 'omschrijving': 'bleekbruin'},
    {'code': 'ral8028', 'r': 81, 'g': 58, 'b': 42, 'omschrijving': 'terrabruin'},
    {'code': 'ral8029', 'r': 127, 'g': 64, 'b': 49, 'omschrijving': 'parelmoer koper'},
    {'code': 'ral9001', 'r': 233, 'g': 224, 'b': 210, 'omschrijving': 'crèmewit'},
    {'code': 'ral9002', 'r': 215, 'g': 213, 'b': 203, 'omschrijving': 'grijswit'},
    {'code': 'ral9003', 'r': 236, 'g': 236, 'b': 231, 'omschrijving': 'signaalwit'},
    {'code': 'ral9004', 'r': 43, 'g': 43, 'b': 44, 'omschrijving': 'signaalzwart'},
    {'code': 'ral9005', 'r': 14, 'g': 14, 'b': 16, 'omschrijving': 'gitzwart'},
    {'code': 'ral9006', 'r': 161, 'g': 161, 'b': 160, 'omschrijving': 'blank aluminiumkleur'},
    {'code': 'ral9007', 'r': 135, 'g': 133, 'b': 129, 'omschrijving': 'grijs aluminiumkleur'},
    {'code': 'ral9010', 'r': 241, 'g': 236, 'b': 225, 'omschrijving': 'zuiverwit'},
    {'code': 'ral9011', 'r': 39, 'g': 41, 'b': 43, 'omschrijving': 'grafietzwart'},
    {'code': 'ral9016', 'r': 241, 'g': 240, 'b': 234, 'omschrijving': 'verkeerswit'},
    {'code': 'ral9017', 'r': 42, 'g': 41, 'b': 42, 'omschrijving': 'verkeerszwart'},
    {'code': 'ral9018', 'r': 200, 'g': 203, 'b': 196, 'omschrijving': 'papyruswit'},
    {'code': 'ral9022', 'r': 133, 'g': 133, 'b': 131, 'omschrijving': 'parelmoer lichtgrijs'},
    {'code': 'ral9023', 'r': 121, 'g': 123, 'b': 122, 'omschrijving': 'parelmoer donkergrijs'}
]

list_of_test_materials = [
    'organisch_bamboe_profiel',
    'organisch_bamboe_plaat',
    'organisch_bamboe_folie',
    'organisch_bamboe_ntb',
    'gips_stuc_generiek',
    'gips_stuc_prefab-element',
    'gips_anhydriet_prefab-element',
    'gips_balsa_vulling',
    'hout_balsa_vulling',
    'hout_balsa_stam',
    'hout_eiken_stam',
    'hout_generiek_tegel',
    'hout_bilinga_tegel',
    'hout_bilinga_ntb',
    'hout_bangkirai_ntb',
    'hout_bangkirai_schaaldeel',
    'hout_bangkirai_profiel',
    'hout_bangkirai_blok',
    'bitumen_asfalt_bedekking',
    'gips_generiek_ihw',
    'gips_generiek_bedekking',
    'gips_asfalt_bedekking',
    'bitumen_asfalt_ntb',
    'steenachtig_kunststeen_klinker_fghgv',
    'samengesteld_element_hek_fghgv',
    'isolatie_fenolhars_vulling_fghgv',
    'isolatie_fenolhars_ntb_fghgv',
    'isolatie_generiek_ntb_fghgv',
    'glas_generiek_ntb',
    'glas_gewapend_ntb',
    'cement_houtwolcement_ihw',
    'cement_generiek_ihw_rew',
    'cement_generiek_blok_rew',
    'gips_generiek_blok_rew',
    'gips_generiek_bedekking_rew',
    'gips_generiek_ihw_test',
    'gips_gipskarton_ihw_test',
    'grondstof_aarde_granulaat',
    'glas_cellulairglas_ntb',
    'glas_gasbeton_ntb',
    'beton_gasbeton_ntb'
]

extra_lijsten = [
    {'omschrijving': 'c12/15', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c20/25', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c30/37', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c28/35', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c35/45', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c45/55', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c53/65', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c55/67', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c60/75', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c70/85', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c80/95', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c90/105', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'c100/115', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'lc12/13', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'lc20/22', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'lc30/33', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'lc40/44', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'lc50/55', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'lc60/66', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'lc70/77', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'lc80/88', 'naam': 'beton', 'soort': 'sterkteklasse'},
    {'omschrijving': 'aangestort', 'naam': 'beton', 'soort': 'bevestiging'},
    {'omschrijving': 'gelast', 'naam': 'beton', 'soort': 'bevestiging'},
    {'omschrijving': 'geschroefd', 'naam': 'beton', 'soort': 'bevestiging'},
    {'omschrijving': 'gestapeld', 'naam': 'beton', 'soort': 'bevestiging'},
    {'omschrijving': 'gestort', 'naam': 'beton', 'soort': 'bevestiging'},
    {'omschrijving': 'mechanisch-bevestigd', 'naam': 'beton', 'soort': 'bevestiging'},
    {'omschrijving': 'opgelegd', 'naam': 'beton', 'soort': 'bevestiging'},
    {'omschrijving': 'verlijmd', 'naam': 'beton', 'soort': 'bevestiging'},
    {'omschrijving': 'gelast', 'naam': 'metaal', 'soort': 'bevestiging'},
    {'omschrijving': 'verlijmd', 'naam': 'metaal', 'soort': 'bevestiging'},
    {'omschrijving': 'gespijkerd', 'naam': 'metaal', 'soort': 'bevestiging'},
    {'omschrijving': 'mechanisch-bevestigd', 'naam': 'metaal', 'soort': 'bevestiging'},
    {'omschrijving': 'geschroefd', 'naam': 'metaal', 'soort': 'bevestiging'},
    {'omschrijving': 'mechanisch-bevestigd', 'naam': 'metaal', 'soort': 'bevestiging'},
    {'omschrijving': 'opgelegd', 'naam': 'metaal', 'soort': 'bevestiging'},
    {'omschrijving': 'onafgewerkt', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'glad', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'geborsteld', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'antislip', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'antislip-wafel', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'antislip-diamant', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'antislip-speciaal', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'gecoat', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'geverfd', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'gerold', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'geschuurd', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'gehydrofobeert', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'dekkend-geschilderd', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'geanodiseerd', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'gecoat', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'gegalvaniseerd', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'geoxideert', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'gepoedercoat', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'geschilderd', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'gespoten', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'thermisch-verzinkt', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'verweerd', 'naam': 'metaal', 'soort': 'afwerking'},
    {'omschrijving': 'schoon', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'vuil', 'naam': 'beton', 'soort': 'afwerking'},
    {'omschrijving': 'hydro', 'naam': 'gips', 'soort': 'specificatie'},
    {'omschrijving': 'zwaar', 'naam': 'gips', 'soort': 'specificatie'},
    {'omschrijving': 'spiegelend', 'naam': 'glas', 'soort': 'specificatie'},
    {'omschrijving': 'bescherm-absorptielaag', 'naam': 'kunststof', 'soort': 'specificatie'},
    {'omschrijving': 'drainage-bufferlaag', 'naam': 'kunststof', 'soort': 'specificatie'},
    {'omschrijving': 'dampremmend', 'naam': 'kunststof', 'soort': 'specificatie'},
    {'omschrijving': 'vochtkerend-dampdoorlatend', 'naam': 'kunststof', 'soort': 'specificatie'},
    {'omschrijving': 'filterlaag', 'naam': 'kunststof', 'soort': 'specificatie'},
    {'omschrijving': 'honingraatvulling', 'naam': 'samengesteld', 'soort': 'specificatie'},
    {'omschrijving': 'optioneel', 'naam': 'samengesteld', 'soort': 'specificatie'},
    {'omschrijving': 'akoestisch', 'naam': 'samengesteld', 'soort': 'specificatie'},
    {'omschrijving': 'geluidwerend', 'naam': 'samengesteld', 'soort': 'specificatie'},
    {'omschrijving': 'hoogglans', 'naam': 'hout', 'soort': 'kwaliteit'},
    {'omschrijving': 'zijdeglans', 'naam': 'hout', 'soort': 'kwaliteit'},
    {'omschrijving': 'mat', 'naam': 'hout', 'soort': 'kwaliteit'},
    {'omschrijving': 'metal', 'naam': 'hout', 'soort': 'kwaliteit'},
    {'omschrijving': 'gepolijst', 'naam': 'metaal', 'soort': 'kwaliteit'},
    {'omschrijving': 'geperforeerd', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gewalsd', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gesmeden', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gegoten', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gepersd', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'geslepen', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gegraveerd', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gestansd', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'geetst', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gesneden', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gefreesd', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'geponsd', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'gesneden-en-gestrekt', 'naam': 'metaal', 'soort': 'bewerking'},
    {'omschrijving': 'waalformaat', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'hilversumsformaat', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'waaldik', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'dikformaat', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'klampsteen', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'lilliput-II', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'goudsesteen', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'lilliput-I', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'ijsselsteen', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'juffertje', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'rijn', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'dordtsesteen', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'brabantsesteen', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'friesedrieling', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'vecht', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'renova', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'maas-formaat', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'engels-formaat', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'utrechtsplat', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'friesemop', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'römer', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'frans', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'moduul-f5', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'smalnf', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'romeins', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'kathedraal-I', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'oud-duits-nf', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'limburgsesteen', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'duitsnormaalformaat', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'kathedraal-II', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'kloostermop-I', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'campina', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'koffertje', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'kloostermop-standaard', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'bijzonder-formaat', 'naam': 'steenachtig', 'soort': 'type steen'},
    {'omschrijving': 'handvorm', 'naam': 'steenachtig', 'soort': 'type uitvoering'},
    {'omschrijving': 'vormbak', 'naam': 'steenachtig', 'soort': 'type uitvoering'},
    {'omschrijving': 'vormraam', 'naam': 'steenachtig', 'soort': 'type uitvoering'},
    {'omschrijving': 'strengpers', 'naam': 'steenachtig', 'soort': 'type uitvoering'},
    {'omschrijving': 'wasserstrich', 'naam': 'steenachtig', 'soort': 'type uitvoering'},
    {'omschrijving': 'halfsteensverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'wildverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'tegelverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'tegeverband-strek', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'tegelverband-kop', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'kettingverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'rollaag', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'rollaag-strek', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'rollaag-kop', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'rollaag-halfsteens', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'blokverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'engelsverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'visgraatverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'kruisverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'hollandsverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'keperverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'bois-cordé', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'deltrap-verband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'kropholler-verband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'fransverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'gotischerverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'klezoorverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'klezorenverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'koppenverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'patijtsverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'noorsverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'koppenverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'patijtsverband ', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'polymetrisch-verband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'ruitverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'spiraalverband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'stammen', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'vlaams-verband', 'naam': 'steenachtig', 'soort': 'verwerking'},
    {'omschrijving': 'horizontaal', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'horizontaal-koppen', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'horizontaal-strekken', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'verticaal', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'verticaal-koppen', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'verticaal-strekken', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'speciaal', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'onder-hoek', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'boog', 'naam': 'steenachtig', 'soort': 'bovenafsluiting'},
    {'omschrijving': 'voeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'voegloos', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'voeg-platvol', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'gladde-voeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'borstelvoeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'verdiepte-voeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'gekamde-voeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'schaduwvoeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'gesneden-voeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'geknipte-voeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'holle-voeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'bol-geklopte-voeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'knipvoeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'open-stootvoeg', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'verlijmd', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'gestapeld', 'naam': 'steenachtig', 'soort': 'voeg'},
    {'omschrijving': 'mechanisch-bevestigd', 'naam': 'steenachtig', 'soort': 'voeg'}
]